In [1]:
import torch
import numpy as np
from torch import nn
from torch import optim

C:\Users\odind\anaconda3\envs\learn_tf_torch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


### Создайте случайный FloatTensor размера 3x4x5

In [3]:
a = torch.Tensor(3,4,5)
a, a.dtype

(tensor([[[7.3634e+02, 8.8562e-43, 7.3634e+02, 8.8562e-43, 6.6031e+02],
          [8.8562e-43, 6.6031e+02, 8.8562e-43, 6.6031e+02, 8.8562e-43],
          [6.6031e+02, 8.8562e-43, 6.6031e+02, 8.8562e-43, 6.6031e+02],
          [8.8562e-43, 1.1811e+04, 8.8562e-43, 7.3767e+02, 8.8562e-43]],
 
         [[1.1829e+04, 8.8562e-43, 1.1829e+04, 8.8562e-43, 8.3512e+03],
          [8.8562e-43, 8.3512e+03, 8.8562e-43, 6.6031e+02, 8.8562e-43],
          [6.6031e+02, 8.8562e-43, 1.1615e+03, 8.8562e-43, 1.1615e+03],
          [8.8562e-43, 8.3170e+03, 8.8562e-43, 8.3170e+03, 8.8562e-43]],
 
         [[1.1594e+03, 8.8562e-43, 9.4642e+03, 8.8562e-43, 1.1215e+04],
          [8.8562e-43, 1.1215e+04, 8.8562e-43, 7.3647e+02, 8.8562e-43],
          [7.3647e+02, 8.8562e-43, 1.1246e+04, 8.8562e-43, 1.1246e+04],
          [8.8562e-43, 1.1197e+04, 8.8562e-43, 1.1197e+04, 8.8562e-43]]]),
 torch.float32)

In [4]:
a = torch.randn(3,4,5)
a, a.dtype

(tensor([[[-1.0081,  0.2108, -0.9213,  0.0522,  0.8581],
          [ 1.0470, -1.7368,  0.8922, -0.0636,  0.9201],
          [-0.6376, -0.4530,  0.2554,  0.2353, -0.3054],
          [-1.9967,  0.2287,  0.5361,  1.7208,  2.1862]],
 
         [[ 0.4197,  1.0758, -0.5443,  0.4352, -1.6536],
          [-1.0385, -0.9716, -0.1908, -0.9593,  0.1091],
          [ 0.0322, -0.6485,  0.2215,  1.4775, -0.3658],
          [ 1.7143,  0.0317,  1.2768, -1.3692,  0.0709]],
 
         [[-1.2102, -1.2505, -0.6242,  1.5749, -0.7130],
          [-1.0612,  0.7150,  0.9426,  1.0958, -1.9147],
          [-1.5947, -1.4107, -2.2074,  0.7683,  0.1294],
          [ 0.1669, -1.0262, -0.2777,  1.0000, -0.3591]]]),
 torch.float32)

### Выведите его форму (shape)

In [5]:
a.shape

torch.Size([3, 4, 5])

### Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [6]:
# этот пункт был ниже, но там размерность другая, переместил выше поэтому

In [7]:
b = torch.tensor([1, 4, 2, 2, 1])
b

tensor([1, 4, 2, 2, 1])

In [8]:
c = a * b
c

tensor([[[-1.0081,  0.8433, -1.8426,  0.1044,  0.8581],
         [ 1.0470, -6.9470,  1.7845, -0.1272,  0.9201],
         [-0.6376, -1.8118,  0.5107,  0.4707, -0.3054],
         [-1.9967,  0.9147,  1.0723,  3.4415,  2.1862]],

        [[ 0.4197,  4.3031, -1.0887,  0.8704, -1.6536],
         [-1.0385, -3.8865, -0.3817, -1.9186,  0.1091],
         [ 0.0322, -2.5939,  0.4430,  2.9550, -0.3658],
         [ 1.7143,  0.1268,  2.5536, -2.7385,  0.0709]],

        [[-1.2102, -5.0020, -1.2484,  3.1498, -0.7130],
         [-1.0612,  2.8599,  1.8853,  2.1916, -1.9147],
         [-1.5947, -5.6429, -4.4148,  1.5367,  0.1294],
         [ 0.1669, -4.1048, -0.5553,  2.0000, -0.3591]]])

### Приведите его к форме 6 X 10

In [9]:
a = a.reshape(6,10)
a, a.shape

(tensor([[-1.0081,  0.2108, -0.9213,  0.0522,  0.8581,  1.0470, -1.7368,  0.8922,
          -0.0636,  0.9201],
         [-0.6376, -0.4530,  0.2554,  0.2353, -0.3054, -1.9967,  0.2287,  0.5361,
           1.7208,  2.1862],
         [ 0.4197,  1.0758, -0.5443,  0.4352, -1.6536, -1.0385, -0.9716, -0.1908,
          -0.9593,  0.1091],
         [ 0.0322, -0.6485,  0.2215,  1.4775, -0.3658,  1.7143,  0.0317,  1.2768,
          -1.3692,  0.0709],
         [-1.2102, -1.2505, -0.6242,  1.5749, -0.7130, -1.0612,  0.7150,  0.9426,
           1.0958, -1.9147],
         [-1.5947, -1.4107, -2.2074,  0.7683,  0.1294,  0.1669, -1.0262, -0.2777,
           1.0000, -0.3591]]),
 torch.Size([6, 10]))

### Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [10]:
d = a @ a.T
d

tensor([[ 8.4080, -0.0450, -0.4996,  2.4213, -2.3415,  4.8102],
        [-0.0450, 12.8926,  0.0504, -4.1430,  2.2544,  1.4523],
        [-0.4996,  0.0504,  7.5445, -0.2901, -0.6816, -0.9865],
        [ 2.4213, -4.1430, -0.2901,  9.2371,  0.9922, -0.0333],
        [-2.3415,  2.2544, -0.6816,  0.9922, 13.7993,  6.8004],
        [ 4.8102,  1.4523, -0.9865, -0.0333,  6.8004, 12.2999]])

In [11]:
d = a.matmul(a.T)
d

tensor([[ 8.4080, -0.0450, -0.4996,  2.4213, -2.3415,  4.8102],
        [-0.0450, 12.8926,  0.0504, -4.1430,  2.2544,  1.4523],
        [-0.4996,  0.0504,  7.5445, -0.2901, -0.6816, -0.9865],
        [ 2.4213, -4.1430, -0.2901,  9.2371,  0.9922, -0.0333],
        [-2.3415,  2.2544, -0.6816,  0.9922, 13.7993,  6.8004],
        [ 4.8102,  1.4523, -0.9865, -0.0333,  6.8004, 12.2999]])

### Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [12]:
# y'_x = 3x^2
# y'_z = 1
# y'_t = -75

In [13]:
x = torch.tensor((1.), requires_grad=True)
z = torch.tensor((0.5), requires_grad=True)
t = torch.tensor((2.), requires_grad=True)

y = x**3 + z - 75*t
y

tensor(-148.5000, grad_fn=<SubBackward0>)

In [14]:
y.backward(x)
x.grad, z.grad, t.grad

(tensor(3.), tensor(1.), tensor(-75.))

### Создайте единичный тензор размера 5x6

In [15]:
a = torch.ones((5,6))
a, a.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([5, 6]))

### Переведите его в формат numpy

In [16]:
a_np = a.numpy()
a_np

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

### Давайте теперь пооптимизируем: возьмите функцию $y = x^{w1} - 2 \cdot x^2 + 5$
#### Посчитайте 

In [17]:
linear = nn.Linear(2, 2, bias=True)
linear.weight, linear.bias

(Parameter containing:
 tensor([[-0.2264,  0.3551],
         [-0.6737, -0.1515]], requires_grad=True),
 Parameter containing:
 tensor([-0.3920, -0.0732], requires_grad=True))

In [18]:
criterion = nn.MSELoss()

optimizer = optim.SGD(linear.parameters(), lr=0.01)

In [19]:
x = torch.randn(2, requires_grad=True)
y = torch.abs(x)**linear.weight - 2 * x**2 + 5
mse = nn.functional.mse_loss(y, x)
x, linear.weight, y, mse

C:\Users\odind\AppData\Local\Temp\ipykernel_7620\4206322250.py:3: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  mse = nn.functional.mse_loss(y, x)


(tensor([ 1.2695, -0.1464], requires_grad=True),
 Parameter containing:
 tensor([[-0.2264,  0.3551],
         [-0.6737, -0.1515]], requires_grad=True),
 tensor([[2.7240, 5.4626],
         [2.6281, 6.2949]], grad_fn=<AddBackward0>),
 tensor(19.2285, grad_fn=<MseLossBackward0>))

In [20]:
optimizer.zero_grad()  # обнуление градиентов перед обучением

In [21]:
pred = linear(x)

In [22]:
loss = criterion(pred, mse)
print('loss', loss, '\nloss_item', loss.item())

loss tensor(401.9036, grad_fn=<MseLossBackward0>) 
loss_item 401.90362548828125


C:\Users\odind\anaconda3\envs\learn_tf_torch\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [23]:
linear.weight.grad, linear.bias.grad

(None, None)

In [24]:
loss.backward()

In [25]:
linear.weight.grad, linear.bias.grad

(tensor([[ -18.7473, -106.2848],
         [ -20.0273, -328.9179]]),
 tensor([-19.9600, -20.1347]))

In [26]:
# optimization

print('BEFORE:\nw: ', linear.weight, '\nb: ', linear.bias)

# step
optimizer.step()

print('\nAFTER:\nw: ', linear.weight, '\nb: ', linear.bias)

BEFORE:
w:  Parameter containing:
tensor([[-0.2264,  0.3551],
        [-0.6737, -0.1515]], requires_grad=True) 
b:  Parameter containing:
tensor([-0.3920, -0.0732], requires_grad=True)

AFTER:
w:  Parameter containing:
tensor([[-0.0390,  1.4179],
        [-0.4734,  3.1377]], requires_grad=True) 
b:  Parameter containing:
tensor([-0.1924,  0.1282], requires_grad=True)
